---
title: "Indice de marginación 2020"
subtitle: "Mapas de México"
author: "Diana Villasana Ocampo"
output:
   html_document:
      highlight: tango
      theme: flatly
      toc: yes
      toc_depth: 2
      toc_float:
        collapsed: yes
---
\usepackage{color}
<style>
body {
text-align: justify;
font-size: 12px}
</style>

<style>
.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #0A2687;
}
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
    color: #ffffff;
    background-color: #09C2BC;
}
</style>

```{r, include=FALSE}
# automatically create a bib database for R packages
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = FALSE, #cache.extra = 
                         eval = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
setwd(here::here())
``` 


```{r, echo = FALSE}
require(showtext)
# activar showtext
showtext_auto()
font_add_google("Montserrat", "montserrat")
```

```{r, echo = FALSE, results=FALSE}
require(dplyr)          #A Grammar of Data Manipulation 
require(forcats)        #Tools for Working with Categorical Variables (Factors)
require(ggplot2)        # Generar gráficos ggplot y la geometría de un mapa
require(ggthemes)       # Extra Themes, scale and Geoms for ggplot2
require(ggrepel)        #Automatically Position Non-Overlapping Text Labels with 'ggplot2'
require(ggmap)          #Spatial Visualization with ggplot2 
require(ggpubr)         #Based Publication Ready Plots with ggplot2
require(grid)
require(gridExtra)
require(knitr)
require(kableExtra)
require(lubridate)
require(openxlsx)
require(readxl)
require(RColorBrewer)   #ColorBrewer Palettes 
require(rgdal)          #Para importar shapefiles. 
require(sp)             # Classes and Methos for Spatial Data
require(spdplyr)        #Data manipulation verbs for the sptial classes
require(tidyverse) 
require(tmap)
require(tmaptools)
require(unikn)          # Paleta de colores
require(viridisLite)    # Paleta de colores 
```



# Zonas Metropolitanas 2020

```{r}
ZM_2020 <- read.xlsx(paste0(here::here(), "/Bases/ZM_2020.xlsx"), startRow = 7) %>%
             filter(CVE_ZM == "09.01") ## Filtro de la ZMVM

# Se guardan los municipios en un vectos 
municipios <- ZM_2020 %>%
               pull(CVE_MUN)
```

### DP2 2020

```{r}
load(file = paste0(here::here(), "/Output/IMC_", 2020, ".RData"))
```

# MGN 2010

```{r,results=FALSE, class.source = "fold-show"}
require(geojsonio)
shape_estados_2020 <- geojsonio::geojson_read(paste0(here::here(), "/Output/estados_2020_json.geojson"), what = "sp")
shape_municipios_2020 <- geojsonio::geojson_read(paste0(here::here(), "/Output/municipios_2020_json.geojson"), what = "sp")
shape_colonias_2020 <- geojsonio::geojson_read(paste0(here::here(), "/Output/colonias_2020_json.geojson"), what = "sp")
```


```{r capas_estados, class.source = "fold-show"}
capas_estados_2020 <- shape_estados_2020 %>%
                       sp::spChFIDs(., str_pad(shape_estados_2020@data$CVE_ENT, 2, "left", pad = "0")) %>%
                        fortify(., id = "CVE_ENT") %>%
                         left_join(., DP2_2020 %>% select("CVE_ENT", "NOM_ENT"), by = c("id" = "CVE_ENT"))

capas_municipios_2020 <- shape_municipios_2020 %>%
                          sp::spChFIDs(., str_pad(shape_municipios_2020@data$CVE_MUN, 5, "left", pad = "0")) %>%
                           fortify(., id = "CVE_MUN") 

capas_colonias_2020 <- shape_colonias_2020 %>%
                        sp::spChFIDs(., str_pad(shape_colonias_2020@data$CVE_COL, 10, "left", pad = "0")) %>%
                         filter(CVE_MUN %in% municipios) %>% 
                          fortify(., id = "CVE_LOC") %>% 
                           left_join(., DP2_2020 %>% select(CVE_COL, GM_2020) %>% 
                                         mutate(GM_2020 = fct_relevel(GM_2020, "Muy alto", "Alto", "Medio", "Bajo", "Muy bajo")), by = c("id" = "CVE_COL")) 
```

```{r}
centroids.df <- as.data.frame(coordinates(shape_estados_2020)) %>%
                 rename("Longitude" = "V1","Latitude" = "V2") %>%
                  mutate(CVE_ENT = shape_estados_2020@data$CVE_ENT)
```



```{r, class.source = "fold-hide"}
paleta <- c("#FC7869", "#F5AE52", "#F7E7FB", "#E0C2F2", "#A478B8")
limites <- capas_colonias_2020 %>%
            summarise(min.x = min(.$long, na.rm = TRUE),
                      max.x = max(.$long, na.rm = TRUE),
                      min.y = min(.$lat, na.rm = TRUE),
                      max.y = max(.$lat, na.rm = TRUE))

p <- ggplot() + 
       geom_polygon(data = capas_municipios_2020,
                      mapping = aes(x = long, 
                                     y = lat, 
                                      group = group),
                       fill = "transparent",
                        color = "dark grey",
                         linewidth = 0.1) +
        geom_polygon(data = capas_colonias_2020,
                      mapping = aes(x = long, 
                                     y = lat, 
                                      group = group,
                                       fill = fct_relevel(GM_2020, "Muy alto", "Alto", "Medio", "Bajo", "Muy bajo"),
                                        color = fct_relevel(GM_2020, "Muy alto", "Alto", "Medio", "Bajo", "Muy bajo")),
                       linewidth = 0.5) + 
        geom_polygon(data = capas_estados_2020,
                      mapping = aes(x = long, 
                                     y = lat, 
                                      group = group),
                       fill = "transparent",
                        color = "black",
                         linewidth = 0.9) +
        geom_label_repel(data = centroids.df,
                          mapping = aes(label = c("Ciudad de México", "Hidalgo", "Estado de México"),
                                        x = Longitude,
                                        y = Latitude), 
                           size = 4, 
                            fill = "#EDEDED",
                             color = "#01007C",
                              alpha = 0.7,
                               force = 0.2,
                                force_pull = 0,
                                 direction = c("both"),
                                  box.padding = 0.25,
                                   point.padding = 0,
                                    segment.colour = "dark grey",
                                     segment.size = 1,
                                      min.segment.length = 0.5) +
          coord_sf(xlim = c(limites$min.x - 5000, limites$max.x + 5000),
                    ylim = c(limites$min.y - 5000 , limites$max.y + 5000)) +
          theme_transparent() + 
           theme(plot.margin = margin(t = 1, r = 1, b = 1, l = 0.5, "cm"),
                  plot.title = element_text(size = 15, hjust = 0.5, vjust = 5, family = "montserrat", face = "bold"),
                   plot.subtitle = element_text(size = 12, vjust = -0.5, family = "montserrat", face = "bold", color = "#757575"),
                   plot.caption = element_text(size = 9, hjust = 0.2, vjust = 1, family = "montserrat"), 
                    legend.key.size = unit(0.5, "cm"),
                     legend.text = element_text(size = 12, family = "montserrat"),   
                      legend.title = element_text(size = 15, hjust = 0.5, vjust = 0.5, family = "montserrat", face = "bold"),
                       legend.position = "right") + 
            scale_fill_manual(values = rev(RColorBrewer::brewer.pal(5, 'YlGnBu'))) + 
             scale_color_manual(values = rev(RColorBrewer::brewer.pal(5, 'YlGnBu'))) + 
          labs(title = "Índice de marginación a nivel colonia, 2020",
                subtitle = "Zona Metropolitana del Valle de México (ZMVM)",
                fill = stringr::str_wrap("Grado de marginación", 10),
                 color = stringr::str_wrap("Grado de marginación", 10))
p
```


```{r, out.width='100%', out.height='100%'}
saveRDS(p, file = paste0(here::here(),"/Output/Mapas_2010-2020.rds"))
```


