# Indicadores simples  {.unlisted .unnumbered}


### Porcentaje de población de 6 a 14 años que no asiste a la escuela $(I_{1}^{i})$ {-}     

El indicador se obtiene dividiendo el monto de población de 6 a 14 años que no asiste a la escuela entre la diferencia de la población total de 6 a 14 años y aquellos que no especificaron su condición de asistencia a la escuela:    

$$I_{1}^{i}=\frac{{PNS}^{i}_{6-14}}{{P}^{i}_{6-14}-{PNEAS}^{i}_{6-14}}\times100$$  

donde:   

$PNS^{i}_{6-14}$: es la población de 6 a 14 años que no asiste a la escuela,   
$P^{i}_{6-14}$: es la población total de 6 a 14 años, y   
$PNEAS^{i}_{6-14}$: es la población de 6 a 14 años que no especificó su condición de asistencia a la escuela.    

### 	Porcentaje de población de 15 años o más sin educación básica $(I_{2}^{i})$ {-}

El indicador mide la magnitud de la población sin educación básica completa. Su cálculo se realiza en dos etapas. En la primera, la población que no especificó su último grado aprobado en secundaria o en estudios técnicos o comerciales con primaria terminada, se distribuye entre la población que aprobó entre uno y dos grados en estos mismos niveles educativos, aplicando la siguiente fórmula:   

$${PSI}_{15+}^{i}={PSCI}_{15+}^i+\left[\frac{{PSCI}_{15+}^i}{{PSCI}_{15+}^i+{PSCC}_{15+}^i}\times{PNEGS}_{15+}^i\right]$$


donde:    

$P{SI}_{15+}^{i}$: es la población de 15 años o más que aprobó entre el primer y segundo grado de secundaria o estudios técnicos o comerciales con primaria terminada con los no especificados de estos niveles educativos ya distribuidos,  
${PSCI}_{15+}^{i}$: es la población de 15 años o más que declaró haber aprobado entre el primer y segundo grado de secundaria o estudios técnicos o comerciales con primaria terminada,  
${PSCC}_{15+}^{i}$: es la población de 15 años o más que cursó el tercer grado en secundaria o tres o cuatro grados en estudios técnicos o comerciales con primaria terminada, y  
${PNEGS}_{15+}^{i}$: es la población de 15 años o más que no especificó su último grado cursado en secundaria o en estudios técnicos o comerciales con primaria terminada.  

Con el dato de la población con estudios truncos en secundaria o en estudios técnicos o comerciales con primaria terminada, se procedió a calcular el indicador de porcentaje de población sin educación básica. Este porcentaje se calcula dividiendo la población de 15 años o más sin educación básica, entre la diferencia de la población total de 15 años o más y aquellos que no especificaron su nivel educativo:   

$$I_{2}^{i}=\frac{{PSIN}_{15+}^i+{PPI}_{15+}^i+{PSI}_{15+}^i}{P_{15+}^i-{PNEIN}_{15+}^i}\times100$$

donde:

${PSIN}_{15+}^{i}$: es la población de 15 años o más sin instrucción,  
${PPI}_{15+}^{i}$: es la población de 15 años o más con algún grado en educación primaria,  
${PSI}_{15+}^{i}$: es la población de 15 años o más con nivel incompleto de secundaria o estudios técnicos o comerciales con primaria terminada,   
$P_{15+}^{i}$: es la población total de 15 años o más, y   
${PNEIN}_{15+}^{i}$: es la población de 15 años o más que no especificó su nivel de instrucción.   


### Porcentaje de población sin derechohabiencia a los servicios de salud $(I_{3}^{i})$ {-}    

En este indicador se identifica a la población sin derechohabiencia a los servicios de salud y se divide entre el total de población menos el número de personas que no especificó su condición de derechohabiencia a los servicios de salud:  

$$I_{3}^{i}=\frac{{PSD}^{i}}{{P}^{i}-{PNESD}^{i}}\times100$$  

donde:    
${PSD}^{i}$: es la población sin derechohabiencia a los servicios de salud,     
${P}^{i}$: es la población total, y    
${PNESD}^{i}$: es la población que no especificó su condición de derechohabiencia a los servicios de salud.    

### Porcentaje de ocupantes en viviendas particulares sin drenaje ni sanitario $(I_{4}^{i})$ {-} 

Este porcentaje se obtiene al dividir el número de ocupantes de viviendas particulares sin drenaje ni sanitario, entre el número de ocupantes en viviendas particulares, menos el número de ocupantes de viviendas particulares en donde no se especificó la disponibilidad de drenaje ni sanitario:  

$$I_{4}^{i}=\frac{{OVSDS}^{i}}{{OVP}^{i}-{ONEDS}^{i}}\times100$$


donde:

${OVSDS}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de drenaje ni sanitario,   
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEDS}^{i}$: son los ocupantes de viviendas particulares en donde no se especificó la disponibilidad de drenaje ni sanitario.    

### Porcentaje de ocupantes en viviendas particulares sin energía eléctrica $(I_{5}^{i})$ {-}

Este indicador se obtiene al dividir el número de ocupantes de viviendas particulares sin disponibilidad de energía eléctrica, entre el número de ocupantes en viviendas particulares menos el número de ocupantes de viviendas particulares en donde no se especificó la existencia de luz eléctrica:   

$$I_{5}^{i}=\frac{{OSEE}^i}{{OVP}^{i}-{ONEEE}^{i}}\times100$$  
donde:   

${OVSDS}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de drenaje ni sanitario,  
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEDS}^{i}$: son los ocupantes de viviendas particulares en donde no se especificó la disponibilidad de drenaje ni sanitario.   


### Porcentaje de ocupantes en viviendas particulares sin agua entubada $(I_{6}^{i})$ {-}     
	
Para obtener este indicador se divide el número de ocupantes en viviendas particulares que no disponen de agua entubada, entre la diferencia del total de ocupantes en viviendas particulares y el total de ocupantes en viviendas en donde no se especificó la disponibilidad de agua entubada:   

$$I_{6}^{i}=\frac{{OSAE}^i}{{OVP}^i-{ONEAE}^i}\times100$$   

donde:  

${OSAE}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de agua entubada,  
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEAE}^{i}$: son los ocupantes de viviendas particulares en donde no se especificó la disponibilidad de agua entubada.   


### Porcentaje de ocupantes en viviendas particulares con piso de tierra $(I_{7}^{i})$ {-}  

En este indicador se identifican los ocupantes de viviendas particulares con piso de tierra y se divide entre el total de ocupantes en viviendas particulares, menos el número de ocupantes de viviendas particulares en donde no se especificó el material predominante en pisos:    

$$I_{7}^{i}=\frac{{OPT}^i}{{OVP}^i-{ONEMP}^i}\times100$$    

donde:   

${OPT}^{i}$: son los ocupantes de viviendas particulares con piso de tierra,    
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEMP}^{i}$: son los ocupantes de viviendas particulares en las que no se especificó el material predominante en pisos.    

### Porcentaje de ocupantes en viviendas particulares con hacinamiento $(I_{8}^{i})$ {-}  

El procedimiento para el cálculo de este indicador constó de dos etapas. Primero, en cada vivienda particular habitada se dividió el número de ocupantes entre el número de cuartos dormitorio, para identificar las viviendas con hacinamiento:    

$$OVHAC=\frac{OVP}{CDVP}$$   
donde:

$VHAC$: es la vivienda con hacinamiento,   
$OVP$: es el número de ocupantes que residen habitualmente una vivienda particular, y    
$CDVP$: es el número de cuartos dormitorio en una vivienda particular.   
	
En la segunda fase de cálculo, se dividió el número de ocupantes en viviendas particulares con hacinamiento, entre el total de ocupantes en viviendas particulares habitadas menos el número de ocupantes en viviendas particulares habitadas donde no se especificó el número de cuartos dormitorio:     

$$I_{8}^{i}=\frac{O{VHAC}^i}{{OVP}^i-{ONECD}^i}\times100$$    

donde:

${OVHAC}^{i}$: son los ocupantes en viviendas particulares con hacinamiento,   
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONECD}^{i}$: son los ocupantes en viviendas particulares en donde no se especificó el número de cuartos dormitorio.     

### Porcentaje de ocupantes en viviendas particulares sin refrigerador $(I_{9}^{i})$ {-}   
	
En este indicador se identifican los ocupantes en viviendas particulares que no disponen de refrigerador y se divide entre el total de ocupantes en viviendas particulares menos los ocupantes en viviendas particulares que no especificaron la disponibilidad de refrigerador:    

$$I_{9}^{i}=\frac{{OSR}^i}{{OVP}^i-{ONER}^i}\times100$$  

donde:   

${OSR}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de refrigerador,     
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y    
${ONER}^{i}$: son los ocupantes de viviendas particulares en donde no se especificó la disponibilidad de refrigerador.   

###  Porcentaje de ocupantes en viviendas particulares sin internet $(I_{10}^{i})$ {-}    

El indicador se calculó dividiendo el número de ocupantes en viviendas particulares que no disponen de servicio de internet, entre el total de ocupantes en viviendas particulares menos los ocupantes en viviendas particulares donde no se especificó la disponibilidad de internet:   

$$I_{10}^{i}=\frac{{OSI}^i}{{OVP}^i-{ONEI}^i}\times100$$  
donde:
${OSI}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de internet,   
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEI}^{i}$: son los ocupantes de viviendas particulares en las que no se especificó la disponibilidad de internet.     


### Porcentaje de ocupantes en viviendas particulares sin celular $(I_{11}^{i})$ {-}    

Este indicador se obtiene dividiendo el número de ocupantes en viviendas particulares que no disponen de celular, entre el total de ocupantes en viviendas particulares menos los ocupantes en viviendas particulares que no especificaron la disponibilidad de celular:   

$$I_{11}^{i}=\frac{{OSC}^i}{{OVP}^i-{ONEC}^i}\times100$$  
donde:
${OSC}^{i}$: son los ocupantes de viviendas particulares sin disponibilidad de celular,    
${OVP}^{i}$: es el total de ocupantes en viviendas particulares, y   
${ONEC}^{i}$: son los ocupantes de viviendas particulares en las que no se especificó la disponibilidad de celular.    

**Indicadores simples**  

```{r}
Indicadores <- c(
                 'Porcentaje de población de 6 a 14 años que no asiste a la escuela', 
                 'Porcentaje de población de 15 años y más sin educación básica',
                 'Porcentaje de población sin derechohabiencia a los servicios de salud',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin drenaje ni excusado',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin energía eléctrica',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin agua entubada',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas con piso de tierra',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas con algún nivel de hacinamiento',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin refrigerador',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin internet',
                 'Porcentaje de ocupantes en viviendas particulares \n habitadas sin celular'
                 )
```
	




	

	
	
 



